set search_path to mhmarket;

insert into location (province, city, barangay, zipcode, district, builtin)
values ('Metro Manila', 'Quezon City', 'Alicia', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Amihan', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Apolonio Samson', '1106', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Baesa', '1106', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Bagbag', '1116', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Bagumbuhay', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Bagong Lipunan ng Crame', '1111', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Bagong Pag-asa', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Bagong Silangan', '1119', 'District 2', true),
       ('Metro Manila', 'Quezon City', 'Bagumbayan', '1110', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Bahay Toro', '1106', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Balingasa', '1115', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Balumbato', '1106', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Batasan Hills', '1126', 'District 2', true),
       ('Metro Manila', 'Quezon City', 'Bayanihan', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Blue Ridge A', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Blue Ridge B', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Botocan', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Bungad', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Camp Aguinaldo', '1110', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Capri', '1117', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Central', '1100', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Claro', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Commonwealth', '1121', 'District 2', true),
       ('Metro Manila', 'Quezon City', 'Culiat', '1128', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Damar', '1115', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Damayan', '1104', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Damayan Lagi', '1112', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Del Monte', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Dioquino Zobel', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Don Manuel', '1113', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Dona Aurora', '1113', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Dona Imelda', '1113', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Dona Josefa', '1113', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Duyan-Duyan', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'E. Rodriguez', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Escopa 1', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Escopa 2', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Escopa 3', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Escopa 4', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Fairview', '1118', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Fairview North', '1121', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Greater Lagro', '1100', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Gulod', '1117', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Holy Spirit', '1127', 'District 2', true),
       ('Metro Manila', 'Quezon City', 'Horseshoe', '1112', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Immaculate Conception', '1111', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Kaligayahan', '1124', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Kalusugan', '1112', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'East Kamias', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Kamuning', '1103', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Katipunan', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Kaunlaran', '1111', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Kristong Hari', '1112', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Krus na Ligas', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Laging Handa', '1103', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Libis', '1110', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Lourdes', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Loyola Heights', '1108', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Maharlika', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Malaya', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Manga', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Manresa', '1115', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Mariana', '1112', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Mariblo', '1104', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Marilag', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Masagana', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Masambong', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Matandang Balara', '1119', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Milagrosa', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Nagkaisang Nayaon', '1125', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'New Era', '1107', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Novaliches', '1123', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Obrero', '1103', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'N.S. Amoranto', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Nayon Kaunlaran', '1104', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Paang Bundok', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Pag-Ibig sa Nayon', '1115', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Paligsahan', '1103', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Paltok', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Pansol', '1108', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Paraiso', '1104', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Pasong Putik', '1118', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Pasong Tamo', '1107', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Payatas', '1119', 'District 2', true),
       ('Metro Manila', 'Quezon City', 'Phil-Am', '1104', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Pinagkaisahan', '1111', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Pinyahan', '1100', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Project 6', '1100', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Quirino 2-A', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Quirino 2-B', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Quirino 2-C', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Quirino 3-A', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Ramon Magsaysay', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Roxas', '1103', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Sacred Heart', '1103', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'San Martin de Porres', '1111', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'St. Ignatius', '1110', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'St. Peter', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Salvacion', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'San Agustin', '1117', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'San Antonio', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'San Bartolome', '1116', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Sangandaan', '1116', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'San Isidro Galas', '1113', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'San Isidro Labrador', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'San Jose', '1115', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'San Roque', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'San Vicente', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Santa Cruz', '1104', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Santa Lucia', '1117', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Santa Monica', '1117', 'District 5', true),
       ('Metro Manila', 'Quezon City', 'Santa Teresita', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Santol', '1113', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Sto. Cristo', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Sto. Domingo', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Santo Nino', '1113', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Sauyo', '1116', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Sienna', '1114', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Sikatuna Village', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Silangan', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Socorro', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'South Triangle', '1103', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Tagumpay', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Talayan', '1104', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Talipapa', '1116', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Tandang Sora', '1116', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'Tatalon', '1113', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Teachers Village East', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Teachers Village West', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Ugong Norte', '1110', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'Unang Sigaw', '1106', 'District 6', true),
       ('Metro Manila', 'Quezon City', 'UP Campus', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'UP Village', '1101', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Valencia', '1112', 'District 4', true),
       ('Metro Manila', 'Quezon City', 'Vasra', '1128', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Veterans Village', '1105', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'Villa Maria Clara', '1109', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'West Triangle', '1104', 'District 1', true),
       ('Metro Manila', 'Quezon City', 'West Kamias', '1102', 'District 3', true),
       ('Metro Manila', 'Quezon City', 'White Plains', '1110', 'District 3', true),
       ('Metro Manila', 'Las Pinas', 'Almanza', '1750', 'District 2', true),
       ('Metro Manila', 'Las Pinas', 'CAA - BF International', '1740', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Daniel Fajardo', '1740', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Elias Aldana', '1740', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Ilaya', '1740', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Manuyo Uno', '1744', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Manuyo Dos', '1744', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Pamplona Uno', '1740', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Pamplona Dos', '1740', 'District 2', true),
       ('Metro Manila', 'Las Pinas', 'Pamplona Tres', '1740', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Pilar', '1740', 'District 2', true),
       ('Metro Manila', 'Las Pinas', 'Pulang Lupa Uno', '1742', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Pulang Lupa Dos', '1742', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'T. S. Cruz Subd.', '1751', 'District 2', true),
       ('Metro Manila', 'Las Pinas', 'Talon Dos', '1751', 'District 2', true),
       ('Metro Manila', 'Las Pinas', 'Talon Kuatro', '1747', 'District 2', true),
       ('Metro Manila', 'Las Pinas', 'Talon Singko', '1747', 'District 2', true),
       ('Metro Manila', 'Las Pinas', 'Talon Tres', '1747', 'District 2', true),
       ('Metro Manila', 'Las Pinas', 'Talon Uno', '1747', 'District 1', true),
       ('Metro Manila', 'Las Pinas', 'Zapote', '1742', 'District 1', true),
       ('Metro Manila', 'Makati', 'Ayala-Paseo de Roxas', '1226', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'Bangkal', '1233', 'District 1', true),
       ('Metro Manila', 'Makati', 'Bel-air', '1209', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'Cembo', '1214', 'District 2', true),
       ('Metro Manila', 'Makati', 'Comembo', '1217', 'District 2', true),
       ('Metro Manila', 'Makati', 'Dasmarinas Village North', '1221', 'District 1', true),
       ('Metro Manila', 'Makati', 'Dasmarinas Village South', '1222', 'District 1', true),
       ('Metro Manila', 'Makati', 'Forbes Park North', '1219', 'District 1', true),
       ('Metro Manila', 'Makati', 'Forbes Park South', '1220', 'District 1', true),
       ('Metro Manila', 'Makati', 'Fort Bonifacio Naval Stn.', '1202', 'District 2', true),
       ('Metro Manila', 'Makati', 'Fort Bonifacio (Camp)', '1201', 'District 2', true),
       ('Metro Manila', 'Makati', 'Greenbelt', '1228', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'Guadalupe Nuevo', '1212', 'District 2', true),
       ('Metro Manila', 'Makati', 'Guadalupe Viejo', '1211', 'District 2', true),
       ('Metro Manila', 'Makati', 'Kasilawan', '1206', 'District 1', true),
       ('Metro Manila', 'Makati', 'La Paz-Singkamas-Tejeros', '1204', 'District 1', true),
       ('Metro Manila', 'Makati', 'Legaspi Village', '1229', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'Magallanes Village', '1232', 'District 1', true),
       ('Metro Manila', 'Makati', 'Makati Commercial Ctr.', '1224', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'Makati CPO + Buendia Ave', '1200', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'Olympia & Carmona', '1207', 'District 1', true),
       ('Metro Manila', 'Makati', 'Palanan', '1235', 'District 1', true),
       ('Metro Manila', 'Makati', 'Pasong Tamo & Ecology Vill', '1231', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'Pembo', '1218', 'District 2', true),
       ('Metro Manila', 'Makati', 'Pinagkaisahan-Pitogo', '1213', 'District 2', true),
       ('Metro Manila', 'Makati', 'Pio del Pilar', '1230', 'District 1', true),
       ('Metro Manila', 'Makati', 'Poblacion', '1210', 'District 1', true),
       ('Metro Manila', 'Makati', 'Rembo (East)', '1216', 'District 2', true),
       ('Metro Manila', 'Makati', 'Rembo (West)', '1215', 'District 2', true),
       ('Metro Manila', 'Makati', 'Salcedo Village', '1227', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'San Antonio Village', '1203', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'San Isidro', '1234', 'District 1', true),
       ('Metro Manila', 'Makati', 'San Lorenzo Village', '1223', 'Makati Central Business District', true),
       ('Metro Manila', 'Makati', 'Sta. Cruz', '1205', 'District 1', true),
       ('Metro Manila', 'Makati', 'Urdaneta Village', '1225', 'District 1', true),
       ('Metro Manila', 'Makati', 'Valenzuela, Santiago, Rizal', '1208', 'District 1', true),
       ('Metro Manila', 'Malabon', 'Acacia', '1474', 'District 2', true),
       ('Metro Manila', 'Malabon', 'Catmon', '1470', 'District 1', true),
       ('Metro Manila', 'Malabon', 'Dampalit', '1480', 'District 1', true),
       ('Metro Manila', 'Malabon', 'Flores', '1471', 'District 1', true),
       ('Metro Manila', 'Malabon', 'Longos', '1472', 'District 2', true),
       ('Metro Manila', 'Malabon', 'Maysilo', '1477', 'District 1', true),
       ('Metro Manila', 'Malabon', 'Muzon', '1479', 'District 1', true),
       ('Metro Manila', 'Malabon', 'Potrero', '1475', 'District 2', true),
       ('Metro Manila', 'Malabon', 'Santolan', '1478', 'District 1', true),
       ('Metro Manila', 'Malabon', 'Tonsuya', '1473', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Addition Hills', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Bagong Silang', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Barangka Drive', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Barangka Ibaba', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Barangka Ilaya', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Barangka Itaas', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Buayang Bato', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Burol', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Daang Bakal', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Hagdan Bato Itaas', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Hagdan Bato Libis', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Harapin Ang Bukas', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Highway Hills', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Hulo', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Mabini–J.Rizal', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Malamig', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Mauway', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Namayan', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'New Zaniga', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Old Zaniga', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Pag-Asa', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Plainview', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Pleasant Hills', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'Poblacion', '1550', 'District 1', true),
       ('Metro Manila', 'Mandaluyong', 'San Jose', '1550', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Vergara', '1551', 'District 2', true),
       ('Metro Manila', 'Mandaluyong', 'Wack-Wack Greenhills', '1551', 'District 1', true),
       ('Metro Manila', 'Manila', 'Binondo', '1006', 'Binondo', true),
       ('Metro Manila', 'Manila', 'Ermita', '', 'Ermita', true),
       ('Metro Manila', 'Manila', 'Intramuros', '1002', 'Intramuros', true),
       ('Metro Manila', 'Manila', 'Malate', '1004', 'Malate', true),
       ('Metro Manila', 'Manila', 'Manila CPO – Ermita', '1000', 'Manila', true),
       ('Metro Manila', 'Manila', 'Paco', '1007', 'Paco', true),
       ('Metro Manila', 'Manila', 'Pandacan', '1011', 'Pandacan', true),
       ('Metro Manila', 'Manila', 'Port Area (South)', '1018', 'Port Area', true),
       ('Metro Manila', 'Manila', 'Quiapo', '1001', 'Quiapo', true),
       ('Metro Manila', 'Manila', 'Sampaloc East', '1008', 'Sampaloc', true),
       ('Metro Manila', 'Manila', 'Sampaloc West', '1015', 'Sampaloc', true),
       ('Metro Manila', 'Manila', 'San Andres Bukid', '1017', 'San Andres', true),
       ('Metro Manila', 'Manila', 'San Miguel', '1005', 'San Miguel', true),
       ('Metro Manila', 'Manila', 'San Nicolas', '1010', 'San Nicolas', true),
       ('Metro Manila', 'Manila', 'Sta. Ana', '1009', 'Sta. Ana', true),
       ('Metro Manila', 'Manila', 'Sta. Cruz North', '1014', 'Sta. Cruz', true),
       ('Metro Manila', 'Manila', 'Sta. Cruz South', '1003', 'Sta. Cruz', true),
       ('Metro Manila', 'Manila', 'Sta. Mesa', '1016', 'Sta. Mesa', true),
       ('Metro Manila', 'Manila', 'Tondo North', '1013', 'Tondo', true),
       ('Metro Manila', 'Manila', 'Tondo South', '1012', 'Tondo', true),
       ('Metro Manila', 'Marikina', 'Barangka', '1803', 'District 1', true),
       ('Metro Manila', 'Marikina', 'Conception 1', '1807', 'District 1', true),
       ('Metro Manila', 'Marikina', 'Conception 2', '1811', 'District 1', true),
       ('Metro Manila', 'Marikina', 'Industrial Valley', '1802', 'District 1', true),
       ('Metro Manila', 'Marikina', 'J de la Pena', '1804', 'District 1', true),
       ('Metro Manila', 'Marikina', 'Malanday', '1805', 'District 1', true),
       ('Metro Manila', 'Marikina', 'Marikina CPO', '1800', '', true),
       ('Metro Manila', 'Marikina', 'Marikina Heights', '1810', 'District 1', true),
       ('Metro Manila', 'Marikina', 'Nangka', '1808', 'District 1', true),
       ('Metro Manila', 'Marikina', 'Parang', '1809', 'District 1', true),
       ('Metro Manila', 'Marikina', 'San Roque-Calumpang', '1801', 'District 1', true),
       ('Metro Manila', 'Marikina', 'Tanong', '1803', 'District 1', true),
       ('Metro Manila', 'Muntinlupa', 'Alabang', '1781', 'District 2', true),
       ('Metro Manila', 'Muntinlupa', 'Ayala Alabang', '1799', 'District 2', true),
       ('Metro Manila', 'Muntinlupa', 'Bayanan', '1772', 'District 1', true),
       ('Metro Manila', 'Muntinlupa', 'Buli', '1771', 'District 2', true),
       ('Metro Manila', 'Muntinlupa', 'Cupang', '1771', 'District 2', true),
       ('Metro Manila', 'Muntinlupa', 'Poblacion', '1776', 'District 1', true),
       ('Metro Manila', 'Muntinlupa', 'Putatan', '1772', 'District 1', true),
       ('Metro Manila', 'Muntinlupa', 'Sucat', '1770', 'District 2', true),
       ('Metro Manila', 'Muntinlupa', 'Tunasan', '1773', 'District 1', true),
       ('Metro Manila', 'Navotas', 'Bagumbayan North (Bagumbayan)', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'Bagumbayan South (Bagumbayan)', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'Bangkulasi (Banculasi)', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'Daanghari', '1409', 'District 2', true),
       ('Metro Manila', 'Navotas', 'Navotas East', '1485', 'District 1', true),
       ('Metro Manila', 'Navotas', 'Navotas West', '1485', 'District 1', true),
       ('Metro Manila', 'Navotas', 'NBBS Dagat-dagatan (North Bay Boulevard South)', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'NBBS Kaunlaran (North Bay Boulevard South)', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'NBBS Proper (North Bay Boulevard South)', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'North Bay Boulevard North', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'San Jose (Poblacion)', '1485', 'District 2', true),
       ('Metro Manila', 'Navotas', 'San Rafael Village', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'San Roque', '1409', 'District 2', true),
       ('Metro Manila', 'Navotas', 'Sipac-Almacen', '1409', 'District 1', true),
       ('Metro Manila', 'Navotas', 'Tangos North (Tangos)', '1489', 'District 2', true),
       ('Metro Manila', 'Navotas', 'Tangos South[c] (Tangos)', '1489', 'District 2', true),
       ('Metro Manila', 'Navotas', 'Tanza 1[d] (Tanza)', '1490', 'District 2', true),
       ('Metro Manila', 'Navotas', 'Tanza 2 (Tanza)', '1490', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'Baclaran', '1702', 'District 1', true),
       ('Metro Manila', 'Paranaque', 'BF Homes', '1720/1718', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'Don Bosco', '1711', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'Don Galo', '1700', 'District 1', true),
       ('Metro Manila', 'Paranaque', 'La Huerta', '1700', 'District 1', true),
       ('Metro Manila', 'Paranaque', 'Marcelo Green', '1700', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'Merville', '1709', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'Moonwalk', '1709', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'San Antonio', '1707/1715', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'San Dionisio', '1700', 'District 1', true),
       ('Metro Manila', 'Paranaque', 'San Isidro', '1700', 'District 1', true),
       ('Metro Manila', 'Paranaque', 'San Martin de Porres', '1700', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'Santo Nino', '1704', 'District 1', true),
       ('Metro Manila', 'Paranaque', 'Sun Valley', '1700', 'District 2', true),
       ('Metro Manila', 'Paranaque', 'Tambo', '1701', 'District 1', true),
       ('Metro Manila', 'Paranaque', 'Vitalez', '1700', 'District 1', true),
       ('Metro Manila', 'Pasay', 'Domestic Airport P.O.', '1301', '', true),
       ('Metro Manila', 'Pasay', 'Manila Bay Reclamation', '1308', '', true),
       ('Metro Manila', 'Pasay', 'Mall of Asia Complex (MOA)', '1300', '', true),
       ('Metro Manila', 'Pasay', 'Pasay City CPO – Malibay', '1300', '', true),
       ('Metro Manila', 'Pasay', 'PICC Reclamation Area', '1307', '', true),
       ('Metro Manila', 'Pasay', 'San Isidro', '1306', '', true),
       ('Metro Manila', 'Pasay', 'San Jose', '1305', '', true),
       ('Metro Manila', 'Pasay', 'San Rafael', '1302', '', true),
       ('Metro Manila', 'Pasay', 'San Roque', '1303', '', true),
       ('Metro Manila', 'Pasay', 'Sta. Clara', '1304', '', true),
       ('Metro Manila', 'Pasay', 'Villamor Airbase', '1309', '', true),
       ('Metro Manila', 'Pasig', 'Bagong Ilog', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Bagong Katipunan', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Bambang', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Buting', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Caniogan', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Dela Paza', '', 'District 2', true),
       ('Metro Manila', 'Pasig', 'Kalawaan', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Kapasigan', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Kapitolyo', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Malinao', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Manggahanb', '', 'District 2', true),
       ('Metro Manila', 'Pasig', 'Maybunga', '', 'District 2', true),
       ('Metro Manila', 'Pasig', 'Oranbo', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Palatiw', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Pinagbuhatan', '', 'District 2', true),
       ('Metro Manila', 'Pasig', 'Pineda', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Rosario', '', 'District 2', true),
       ('Metro Manila', 'Pasig', 'Sagad', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'San Antonio', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'San Joaquin', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'San Jose', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'San Miguel', '', 'District 2', true),
       ('Metro Manila', 'Pasig', 'San Nicolas', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Santa Cruz', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Santa Lucia', '', 'District 2', true),
       ('Metro Manila', 'Pasig', 'Santa Rosa', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Santo Tomas', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Santolan', '', 'District 2', true),
       ('Metro Manila', 'Pasig', 'Sumilang', '', 'Distrct 1', true),
       ('Metro Manila', 'Pasig', 'Ugong', '', 'Distrct 1', true),
       ('Metro Manila', 'Pateros', 'Aguho', '1620', '', true),
       ('Metro Manila', 'Pateros', 'Sta. Ana', '1621', '', true),
       ('Metro Manila', 'San Juan', 'Addition Hills', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Balong–Bato', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Batis', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Corazon de Jesus', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Ermitano', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Greenhills', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Isabelita', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Kabayanan', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Little Baguio', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Maytunas', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Onse', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Pasadena', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Pedro Cruz', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Progreso', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Rivera', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Saint Joseph (Halo-Halo)', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Salapan', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'San Perfecto', '', 'District 1', true),
       ('Metro Manila', 'San Juan', 'Santa Lucia', '', 'District 2', true),
       ('Metro Manila', 'San Juan', 'Tibagan', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Bagong Tanyag', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Bagumbayan', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Bambang', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Calzada', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Central Bicutan', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Central Signal Village', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Fort Bonifacio', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Hagonoy', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Ibayo Tipas', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Katuparan', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Ligid Tipas', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Lower Bicutan', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Maharlika Village', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Napindan', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'New Lower Bicutan', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'North Daang Hari', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'North Signal Village', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Palingon', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Pinagsama', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'San Miguel', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Santa Ana', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'South Daang Hari', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'South Signal Village', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Tuktukan', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Upper Bicutan', '', 'District 2', true),
       ('Metro Manila', 'Taguig', 'Ususan', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Wawa', '', 'District 1', true),
       ('Metro Manila', 'Taguig', 'Western Bicutan', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Arkong Bato', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Bagbaguin', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Balangkas', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Bignay', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Bisig', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Canumay East', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Canumay West', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Coloong', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Dalandanan', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Gen. T. de Leon', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Isla', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Karuhatan', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Lawang Bato', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Lingunan', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Mabolo', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Malanday', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Malinta', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Mapulang Lupa', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Marulas', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Maysan', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Palasan', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Parada', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Pariancillo Villa', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Paso de Blas', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Pasolo', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Poblacion', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Polo', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Punturin', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Rincon', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Tagalag', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Ugong', '', 'District 2', true),
       ('Metro Manila', 'Valenzuela', 'Veinte Reales', '', 'District 1', true),
       ('Metro Manila', 'Valenzuela', 'Wawang Pulo', '', 'District 1', true);